package dev.erst.fingrind.core;

import java.util.List;

/** Canonical kinds for durable postings committed into one protected FinGrind book. */
public enum PostingKind implements WireValue {
  STANDARD,
  OPENING_BALANCE,
  INTERIM_RESULT_SWEEP,
  FISCAL_YEAR_CLOSE;

  @Override
  public String wireValue() {
    return switch (this) {
      case STANDARD -> "STANDARD";
      case OPENING_BALANCE -> "OPENING_BALANCE";
      case INTERIM_RESULT_SWEEP -> "INTERIM_RESULT_SWEEP";
      case FISCAL_YEAR_CLOSE -> "FISCAL_YEAR_CLOSE";
    };
  }

  /** Returns every stable wire value for durable posting kinds. */
  public static List<String> wireValues() {
    return WireValue.wireValues(PostingKind.class);
  }

  /** Parses one stable posting-kind wire value. */
  public static PostingKind fromWireValue(String wireValue) {
    return WireValue.fromWireValue(PostingKind.class, wireValue, "Unsupported postingKind");
  }

  /** Returns whether this posting is one ordinary business posting rather than a close entry. */
  public boolean isStandard() {
    return this == STANDARD;
  }

  /** Returns whether this posting is one explicit opening-balance seed entry. */
  public boolean isOpeningBalance() {
    return this == OPENING_BALANCE;
  }

  /** Returns whether this posting kind is generated by FinGrind rather than caller-authored. */
  public boolean isGenerated() {
    return switch (this) {
      case INTERIM_RESULT_SWEEP, FISCAL_YEAR_CLOSE -> true;
      case STANDARD, OPENING_BALANCE -> false;
    };
  }
}
