org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
group=dev.erst.fingrind
version=0.34.0
fingrindDescription=Command-line double-entry bookkeeping with one protected book per accounting entity
fingrindManagedSqlitePackageId=sqlite3mc-amalgamation-2.3.4-sqlite-3530001
fingrindManagedSqliteSourceSha3=e4d6fe92d776ccca57e50fc13dec430c64b88b46b05c4ffb97eb2265842f45c2
