target-version = "py312"
line-length = 100

include = [
  "scripts/**/*.py",
]

exclude = [
  ".git",
  ".gradle",
  ".ruff_cache",
  "build",
  "tmp",
]

[lint]
extend-select = [
  "B",
  "I",
  "RUF",
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
