package dev.erst.fingrind.contract;

import dev.erst.fingrind.contract.protocol.LedgerAssertionKind;
import dev.erst.fingrind.contract.protocol.LedgerStepKind;
import dev.erst.fingrind.contract.protocol.OperationId;
import dev.erst.fingrind.contract.protocol.ProtocolCatalog;
import dev.erst.fingrind.contract.protocol.ProtocolDeclareAccountFields;
import dev.erst.fingrind.contract.protocol.ProtocolLedgerPlanFields;
import dev.erst.fingrind.contract.protocol.ProtocolPostEntryFields;
import dev.erst.fingrind.core.ActorType;
import dev.erst.fingrind.core.JournalLine;
import dev.erst.fingrind.core.NormalBalance;
import java.util.List;

/** Builds request-shape descriptors for the machine-readable contract. */
final class MachineContractRequestShapeSupport {
  private MachineContractRequestShapeSupport() {}

  static ContractRequestShapes.RequestShapesDescriptor requestShapes() {
    return new ContractRequestShapes.RequestShapesDescriptor(
        postEntryShape(), declareAccountShape(), ledgerPlanShape());
  }

  private static ContractRequestShapes.PostEntryRequestShapeDescriptor postEntryShape() {
    return new ContractRequestShapes.PostEntryRequestShapeDescriptor(
        List.of(
            requiredField(
                ProtocolPostEntryFields.TopLevel.EFFECTIVE_DATE,
                "ISO-8601 local date that makes the journal entry effective."),
            requiredField(
                ProtocolPostEntryFields.TopLevel.LINES,
                "Balanced non-empty array of journal lines for one currency."),
            requiredField(
                ProtocolPostEntryFields.TopLevel.PROVENANCE,
                "Caller-supplied request provenance captured before commit."),
            optionalField(
                ProtocolPostEntryFields.TopLevel.REVERSAL,
                "Optional reversal target descriptor for additive reversal postings."),
            forbiddenField(
                ProtocolPostEntryFields.TopLevel.CORRECTION,
                "Legacy correction payloads are hard-broken and no longer accepted.")),
        List.of(
            requiredField(
                ProtocolPostEntryFields.JournalLine.ACCOUNT_CODE,
                "Declared book-local account code for this journal line."),
            requiredField(
                ProtocolPostEntryFields.JournalLine.SIDE,
                "Journal side that carries the line amount."),
            requiredField(
                ProtocolPostEntryFields.JournalLine.CURRENCY_CODE,
                "Three-letter ISO currency code shared by every line in the entry."),
            requiredField(
                ProtocolPostEntryFields.JournalLine.AMOUNT,
                "Plain decimal string greater than zero without exponent notation.")),
        List.of(
            requiredField(
                ProtocolPostEntryFields.Provenance.ACTOR_ID,
                "Stable identifier of the actor that initiated the request."),
            requiredField(
                ProtocolPostEntryFields.Provenance.ACTOR_TYPE,
                "Actor classification from the live actorType enum vocabulary."),
            requiredField(
                ProtocolPostEntryFields.Provenance.COMMAND_ID,
                "Caller-generated command identity for this request."),
            requiredField(
                ProtocolPostEntryFields.Provenance.IDEMPOTENCY_KEY,
                "Book-local idempotency key used to detect duplicate commit attempts."),
            requiredField(
                ProtocolPostEntryFields.Provenance.CAUSATION_ID,
                "Caller-supplied causation identifier for upstream traceability."),
            optionalField(
                ProtocolPostEntryFields.Provenance.CORRELATION_ID,
                "Optional correlation identifier for joining related calls."),
            forbiddenField(
                ProtocolPostEntryFields.Provenance.RECORDED_AT,
                "Committed audit timestamps are generated by FinGrind, not caller input."),
            forbiddenField(
                ProtocolPostEntryFields.Provenance.SOURCE_CHANNEL,
                "Committed source channel is generated by FinGrind, not caller input.")),
        List.of(
            requiredField(
                ProtocolPostEntryFields.Reversal.PRIOR_POSTING_ID,
                "Existing committed posting identifier that this request reverses."),
            requiredField(
                ProtocolPostEntryFields.Reversal.REASON,
                "Human-readable operator explanation attached to this reversal."),
            forbiddenField(
                ProtocolPostEntryFields.Reversal.KIND,
                "Legacy reversal-kind routing is removed; FinGrind is reversal-only.")),
        List.of(
            enumVocabulary("lineSide", JournalLine.EntrySide.wireValues()),
            enumVocabulary("actorType", ActorType.wireValues())));
  }

  private static ContractRequestShapes.DeclareAccountRequestShapeDescriptor declareAccountShape() {
    return new ContractRequestShapes.DeclareAccountRequestShapeDescriptor(
        List.of(
            requiredField(
                ProtocolDeclareAccountFields.ACCOUNT_CODE,
                "Book-local account code used by journal lines."),
            requiredField(
                ProtocolDeclareAccountFields.ACCOUNT_NAME,
                "Non-blank display name for the declared account."),
            requiredField(
                ProtocolDeclareAccountFields.NORMAL_BALANCE,
                "Side of the journal equation that increases the account.")),
        List.of(enumVocabulary("normalBalance", NormalBalance.wireValues())));
  }

  private static ContractRequestShapes.LedgerPlanRequestShapeDescriptor ledgerPlanShape() {
    return new ContractRequestShapes.LedgerPlanRequestShapeDescriptor(
        List.of(
            requiredField(
                ProtocolLedgerPlanFields.Plan.PLAN_ID, "Caller-supplied plan identifier."),
            requiredField(
                ProtocolLedgerPlanFields.Plan.STEPS,
                "Ordered non-empty array of executable ledger-plan steps.")),
        List.of(
            requiredField(
                ProtocolLedgerPlanFields.Step.STEP_ID,
                "Caller-supplied step identifier unique inside the plan."),
            requiredField(
                ProtocolLedgerPlanFields.Step.KIND,
                "Canonical ledger-plan step kind for this step."),
            optionalField(
                ProtocolLedgerPlanFields.Step.POSTING,
                "Posting request payload for "
                    + operation(OperationId.POST_ENTRY)
                    + " and "
                    + operation(OperationId.PREFLIGHT_ENTRY)
                    + " steps."),
            optionalField(
                ProtocolLedgerPlanFields.Step.DECLARE_ACCOUNT,
                "Account declaration payload for "
                    + operation(OperationId.DECLARE_ACCOUNT)
                    + " steps."),
            optionalField(
                ProtocolLedgerPlanFields.Step.QUERY,
                "Query payload for list steps and "
                    + operation(OperationId.ACCOUNT_BALANCE)
                    + " steps."),
            optionalField(
                ProtocolLedgerPlanFields.Step.ASSERTION,
                "Assertion payload for first-class assertion steps."),
            optionalField(
                ProtocolLedgerPlanFields.Step.POSTING_ID,
                "Posting identifier for " + operation(OperationId.GET_POSTING) + " steps.")),
        List.of(
            optionalField(
                ProtocolLedgerPlanFields.Query.ACCOUNT_CODE,
                "Optional account filter for "
                    + operation(OperationId.LIST_POSTINGS)
                    + ", required account for "
                    + operation(OperationId.ACCOUNT_BALANCE)
                    + "."),
            optionalField(
                ProtocolLedgerPlanFields.Query.EFFECTIVE_DATE_FROM,
                "Inclusive ISO-8601 effective-date lower bound."),
            optionalField(
                ProtocolLedgerPlanFields.Query.EFFECTIVE_DATE_TO,
                "Inclusive ISO-8601 effective-date upper bound."),
            optionalField(ProtocolLedgerPlanFields.Query.LIMIT, "Page size for list steps."),
            optionalField(
                ProtocolLedgerPlanFields.Query.CURSOR,
                "Opaque cursor for continuing "
                    + operation(OperationId.LIST_POSTINGS)
                    + " from the prior page."),
            optionalField(
                ProtocolLedgerPlanFields.Query.OFFSET,
                "Page offset for " + operation(OperationId.LIST_ACCOUNTS) + " steps.")),
        List.of(
            requiredField(
                ProtocolLedgerPlanFields.Assertion.KIND,
                "Canonical assertion kind nested inside an assert step."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.ACCOUNT_CODE,
                "Account code consumed by account assertions."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.POSTING_ID,
                "Posting identifier consumed by posting-existence assertions."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.EFFECTIVE_DATE_FROM,
                "Inclusive ISO-8601 effective-date lower bound for balance assertions."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.EFFECTIVE_DATE_TO,
                "Inclusive ISO-8601 effective-date upper bound for balance assertions."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.CURRENCY_CODE,
                "Currency bucket expected by "
                    + operation(OperationId.ACCOUNT_BALANCE)
                    + " assertions."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.NET_AMOUNT,
                "Plain decimal expected net amount for "
                    + operation(OperationId.ACCOUNT_BALANCE)
                    + " assertions."),
            optionalField(
                ProtocolLedgerPlanFields.Assertion.BALANCE_SIDE,
                "Expected normal-balance side for "
                    + operation(OperationId.ACCOUNT_BALANCE)
                    + " assertions.")),
        List.of(LedgerStepKind.OPEN_BOOK.wireValue(), LedgerStepKind.DECLARE_ACCOUNT.wireValue()),
        List.of(
            LedgerStepKind.INSPECT_BOOK.wireValue(),
            LedgerStepKind.LIST_ACCOUNTS.wireValue(),
            LedgerStepKind.GET_POSTING.wireValue(),
            LedgerStepKind.LIST_POSTINGS.wireValue(),
            LedgerStepKind.ACCOUNT_BALANCE.wireValue()),
        List.of(LedgerStepKind.PREFLIGHT_ENTRY.wireValue(), LedgerStepKind.POST_ENTRY.wireValue()),
        LedgerStepKind.ASSERT.wireValue(),
        LedgerAssertionKind.wireValues(),
        MachineContractDomainSupport.planExecution());
  }

  private static ContractRequestShapes.EnumVocabularyDescriptor enumVocabulary(
      String name, List<String> values) {
    return new ContractRequestShapes.EnumVocabularyDescriptor(name, values);
  }

  private static ContractRequestShapes.RequestFieldDescriptor requiredField(
      String name, String description) {
    return new ContractRequestShapes.RequestFieldDescriptor(name, "required", description);
  }

  private static ContractRequestShapes.RequestFieldDescriptor optionalField(
      String name, String description) {
    return new ContractRequestShapes.RequestFieldDescriptor(name, "optional", description);
  }

  private static ContractRequestShapes.RequestFieldDescriptor forbiddenField(
      String name, String description) {
    return new ContractRequestShapes.RequestFieldDescriptor(name, "forbidden", description);
  }

  private static String operation(OperationId operationId) {
    return ProtocolCatalog.operationName(operationId);
  }
}
