package dev.erst.fingrind.contract;

import dev.erst.fingrind.contract.protocol.BookModelFacts;
import dev.erst.fingrind.contract.protocol.CurrencyFacts;
import dev.erst.fingrind.contract.protocol.OperationId;
import dev.erst.fingrind.contract.protocol.PlanExecutionFacts;
import dev.erst.fingrind.contract.protocol.ProtocolCatalog;
import dev.erst.fingrind.contract.protocol.ProtocolDeclareAccountFields;
import dev.erst.fingrind.contract.protocol.ProtocolOperation;
import dev.erst.fingrind.contract.protocol.ProtocolPostEntryFields;
import dev.erst.fingrind.core.NormalBalance;
import java.util.List;

/** Builds the non-request/non-response descriptor families in the machine contract. */
final class MachineContractDomainSupport {
  private MachineContractDomainSupport() {}

  static ContractResponse.BookModelDescriptor bookModel() {
    BookModelFacts bookModel = ProtocolCatalog.bookModel();
    return new ContractResponse.BookModelDescriptor(
        bookModel.boundary(),
        bookModel.entityScope(),
        bookModel.filesystem(),
        bookModel.credential(),
        bookModel.initialization(),
        bookModel.accountRegistry(),
        bookModel.migration(),
        bookModel.currencyScope());
  }

  static List<ContractDiscovery.CommandDescriptor> commandDescriptors() {
    return ProtocolCatalog.operations().stream()
        .map(MachineContractDomainSupport::commandDescriptor)
        .toList();
  }

  static List<ContractDiscovery.ExitCodeDescriptor> exitCodes() {
    return List.of(
        new ContractDiscovery.ExitCodeDescriptor(0, "successful command"),
        new ContractDiscovery.ExitCodeDescriptor(1, "runtime or environment failure"),
        new ContractDiscovery.ExitCodeDescriptor(2, "invalid request or deterministic rejection"),
        new ContractDiscovery.ExitCodeDescriptor(
            3,
            "valid "
                + ProtocolCatalog.operationName(OperationId.EXECUTE_PLAN)
                + " request whose assertion step failed"));
  }

  static ContractResponse.AuditDescriptor audit() {
    return new ContractResponse.AuditDescriptor(
        List.of(
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.ACTOR_ID,
                "Stable identifier of the actor that initiated the request."),
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.ACTOR_TYPE,
                "Actor classification from the live actorType enum vocabulary."),
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.COMMAND_ID,
                "Caller-generated command identity for this request."),
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.IDEMPOTENCY_KEY,
                "Book-local idempotency key supplied by the caller."),
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.CAUSATION_ID,
                "Caller-supplied causation identifier."),
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.CORRELATION_ID,
                "Optional caller-supplied correlation identifier.")),
        List.of(
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.RECORDED_AT,
                "Commit timestamp generated by FinGrind at durable write time."),
            new ContractResponse.FieldDescriptor(
                ProtocolPostEntryFields.Provenance.SOURCE_CHANNEL,
                "Committed request channel generated by FinGrind.")));
  }

  static ContractResponse.AccountRegistryDescriptor accountRegistry() {
    return new ContractResponse.AccountRegistryDescriptor(
        true,
        "redeclaration may update the display name and reactivate an inactive account, but will not amend normalBalance",
        List.of(
            new ContractResponse.FieldDescriptor(
                ProtocolDeclareAccountFields.ACCOUNT_CODE, "Book-local account code to declare."),
            new ContractResponse.FieldDescriptor(
                ProtocolDeclareAccountFields.ACCOUNT_NAME,
                "Non-blank display name for the account."),
            new ContractResponse.FieldDescriptor(
                ProtocolDeclareAccountFields.NORMAL_BALANCE,
                "Journal side that increases the account.")),
        List.of(
            new ContractResponse.FieldDescriptor(
                "accountCode", "Declared book-local account code."),
            new ContractResponse.FieldDescriptor(
                "accountName", "Current display name of the account."),
            new ContractResponse.FieldDescriptor("normalBalance", "Declared normal balance side."),
            new ContractResponse.FieldDescriptor(
                "active", "Whether the account currently accepts postings."),
            new ContractResponse.FieldDescriptor(
                "declaredAt", "Clock timestamp of the first declaration.")),
        List.of(
            new ContractRequestShapes.EnumVocabularyDescriptor(
                "normalBalance", NormalBalance.wireValues())));
  }

  static ContractResponse.ReversalDescriptor reversals() {
    return new ContractResponse.ReversalDescriptor(
        "reversal-only",
        List.of(
            "book-must-be-initialized",
            "every-line-account-must-be-declared-and-active",
            "target-must-exist-in-book",
            "reversal-object-must-carry-human-readable-reason",
            "one-reversal-per-target",
            "reversal-must-negate-target"));
  }

  static ContractResponse.PreflightDescriptor preflight() {
    dev.erst.fingrind.contract.protocol.PreflightFacts preflight = ProtocolCatalog.preflight();
    return new ContractResponse.PreflightDescriptor(
        preflight.semantics(), preflight.commitGuarantee(), preflight.description());
  }

  static ContractResponse.CurrencyDescriptor currencyModel() {
    CurrencyFacts currency = ProtocolCatalog.currency();
    return new ContractResponse.CurrencyDescriptor(
        currency.scope(), currency.multiCurrencyStatus(), currency.description());
  }

  static ContractResponse.PlanExecutionDescriptor planExecution() {
    PlanExecutionFacts facts = ProtocolCatalog.planExecution();
    return new ContractResponse.PlanExecutionDescriptor(
        facts.transactionMode(), facts.failurePolicy(), facts.journal(), facts.hardLimitations());
  }

  private static ContractDiscovery.CommandDescriptor commandDescriptor(
      ProtocolOperation operation) {
    return new ContractDiscovery.CommandDescriptor(
        operation.id().wireName(),
        operation.aliases(),
        operation.options(),
        operation.executionMode().wireValue(),
        operation.outputModes(),
        operation.artifactOutputs().stream()
            .map(
                artifact ->
                    new ContractDiscovery.ArtifactOutputDescriptor(
                        artifact.format(), artifact.option(), artifact.description()))
            .toList(),
        operation.analysisSummary());
  }
}
