from __future__ import annotations

from typing import Final

ACCOUNT_LEDGER_CSV_HEADER: Final[list[str]] = [
    "exportFamily",
    "rowId",
    "parentRowId",
    "relationKind",
    "recordKind",
    "accountCode",
    "accountName",
    "accountType",
    "accountRole",
    "normalBalance",
    "active",
    "effectiveDateFrom",
    "effectiveDateTo",
    "currencyCode",
    "openingDebitTotal",
    "openingCreditTotal",
    "openingNetAmount",
    "openingBalanceSide",
    "closingDebitTotal",
    "closingCreditTotal",
    "closingNetAmount",
    "closingBalanceSide",
    "effectiveDate",
    "recordedAt",
    "postingId",
    "postingKind",
    "postingOriginKind",
    "reversalState",
    "reversalTarget",
    "debitAmount",
    "creditAmount",
    "runningNetAmount",
    "runningBalanceSide",
    "counterpartAccountCode",
    "sourceDocumentId",
    "sourceDocumentType",
    "approvalId",
    "approvalDecision",
    "message",
]


def account_ledger_base_row(record_kind: str, **overrides: str) -> dict[str, str]:
    base = {
        "exportFamily": "",
        "rowId": "",
        "parentRowId": "",
        "relationKind": "",
        "recordKind": record_kind,
        "accountCode": "cash",
        "accountName": "Cash",
        "accountType": "ASSET",
        "accountRole": "ORDINARY",
        "normalBalance": "DEBIT",
        "active": "true",
        "effectiveDateFrom": "2026-04-07",
        "effectiveDateTo": "2026-04-08",
        "currencyCode": "",
        "openingDebitTotal": "",
        "openingCreditTotal": "",
        "openingNetAmount": "",
        "openingBalanceSide": "",
        "closingDebitTotal": "",
        "closingCreditTotal": "",
        "closingNetAmount": "",
        "closingBalanceSide": "",
        "effectiveDate": "",
        "recordedAt": "",
        "postingId": "",
        "postingKind": "",
        "postingOriginKind": "",
        "reversalState": "",
        "reversalTarget": "",
        "debitAmount": "",
        "creditAmount": "",
        "runningNetAmount": "",
        "runningBalanceSide": "",
        "counterpartAccountCode": "",
        "sourceDocumentId": "",
        "sourceDocumentType": "",
        "approvalId": "",
        "approvalDecision": "",
        "message": "",
    }
    base.update(overrides)
    return base


def account_ledger_movement_row(
    effective_date: str,
    recorded_at: str,
    posting_id: str,
    posting_origin_kind: str,
    *,
    debit: str,
    credit: str,
    running_net: str,
) -> dict[str, str]:
    return account_ledger_base_row(
        "entry",
        exportFamily="posting-relationships",
        rowId="ledger-entry:" + posting_id,
        relationKind="entry",
        currencyCode="EUR",
        effectiveDate=effective_date,
        recordedAt=recorded_at,
        postingId=posting_id,
        postingKind="STANDARD",
        postingOriginKind=posting_origin_kind,
        reversalState="direct",
        debitAmount=debit,
        creditAmount=credit,
        runningNetAmount=running_net,
        runningBalanceSide="DEBIT",
    )
