from __future__ import annotations

from typing import Final

ACCOUNT_LEDGER_CSV_HEADER: Final[list[str]] = [
    "exportFamily",
    "rowId",
    "parentRowId",
    "relationKind",
    "recordKind",
    "accountCode",
    "accountName",
    "accountType",
    "normalBalance",
    "active",
    "effectiveDateFrom",
    "effectiveDateTo",
    "currencyCode",
    "openingDebitTotal",
    "openingCreditTotal",
    "openingNetAmount",
    "openingBalanceSide",
    "closingDebitTotal",
    "closingCreditTotal",
    "closingNetAmount",
    "closingBalanceSide",
    "effectiveDate",
    "recordedAt",
    "postingId",
    "postingKind",
    "postingOriginKind",
    "reversalState",
    "reversalTarget",
    "debitAmount",
    "creditAmount",
    "runningNetAmount",
    "runningBalanceSide",
    "counterpartAccountCode",
    "sourceDocumentId",
    "sourceDocumentType",
    "approvalId",
    "approvalDecision",
    "message",
]


def account_ledger_csv_row(
    *,
    row_id: str,
    parent_row_id: str = "",
    relation_kind: str,
    record_kind: str = "account-ledger",
    account_code: str = "cash",
    account_name: str = "Cash",
    account_type: str = "ASSET",
    normal_balance: str = "DEBIT",
    active: str = "true",
    effective_date_from: str = "",
    effective_date_to: str = "",
    currency_code: str = "",
    opening_debit_total: str = "",
    opening_credit_total: str = "",
    opening_net_amount: str = "",
    opening_balance_side: str = "",
    closing_debit_total: str = "",
    closing_credit_total: str = "",
    closing_net_amount: str = "",
    closing_balance_side: str = "",
    effective_date: str = "",
    recorded_at: str = "",
    posting_id: str = "",
    posting_kind: str = "",
    posting_origin_kind: str = "",
    reversal_state: str = "",
    reversal_target: str = "",
    debit_amount: str = "",
    credit_amount: str = "",
    running_net_amount: str = "",
    running_balance_side: str = "",
    counterpart_account_code: str = "",
    source_document_id: str = "",
    source_document_type: str = "",
    approval_id: str = "",
    approval_decision: str = "",
    message: str = "",
) -> dict[str, str]:
    return {
        "exportFamily": "account-ledger",
        "rowId": row_id,
        "parentRowId": parent_row_id,
        "relationKind": relation_kind,
        "recordKind": record_kind,
        "accountCode": account_code,
        "accountName": account_name,
        "accountType": account_type,
        "normalBalance": normal_balance,
        "active": active,
        "effectiveDateFrom": effective_date_from,
        "effectiveDateTo": effective_date_to,
        "currencyCode": currency_code,
        "openingDebitTotal": opening_debit_total,
        "openingCreditTotal": opening_credit_total,
        "openingNetAmount": opening_net_amount,
        "openingBalanceSide": opening_balance_side,
        "closingDebitTotal": closing_debit_total,
        "closingCreditTotal": closing_credit_total,
        "closingNetAmount": closing_net_amount,
        "closingBalanceSide": closing_balance_side,
        "effectiveDate": effective_date,
        "recordedAt": recorded_at,
        "postingId": posting_id,
        "postingKind": posting_kind,
        "postingOriginKind": posting_origin_kind,
        "reversalState": reversal_state,
        "reversalTarget": reversal_target,
        "debitAmount": debit_amount,
        "creditAmount": credit_amount,
        "runningNetAmount": running_net_amount,
        "runningBalanceSide": running_balance_side,
        "counterpartAccountCode": counterpart_account_code,
        "sourceDocumentId": source_document_id,
        "sourceDocumentType": source_document_type,
        "approvalId": approval_id,
        "approvalDecision": approval_decision,
        "message": message,
    }
