from __future__ import annotations

STANDARD_LIST_POSTINGS_TEXT = (
    "Postings\n"
    "========\n\n"
    "Returned postings : 2\n"
    "Limit             : 50\n"
    "Next cursor       : (none)\n\n"
    "2026-04-08 | Direct\n"
    "-------------------\n"
    "Role              : Direct\n"
    "Debit             : 4.00\n"
    "Credit            : 0.00\n"
    "Accounts          : Cash\n"
    "Posting ref       : posting-2\n"
    "Attestation order : 2\n\n"
    "2026-04-07 | Direct\n"
    "-------------------\n"
    "Role              : Direct\n"
    "Debit             : 10.00\n"
    "Credit            : 0.00\n"
    "Accounts          : Cash\n"
    "Posting ref       : posting-1\n"
    "Attestation order : 1\n"
)
STANDARD_ACCOUNT_BALANCE_TEXT = (
    "Account Balance\n"
    "===============\n\n"
    "Account : Cash [cash]\n"
    "Range   : book start to current book horizon\n\n"
    "Currency | Debit total | Credit total | Net amount | Balance side\n"
    "---------+-------------+--------------+------------+-------------\n"
    "EUR      |       10.00 |         4.00 |       6.00 | Debit\n\n"
    "Context\n"
    "-------\n"
    "Entity              : Acme Studio\n"
    "Seed template       : Owner-managed service seed template\n"
    "Accounting basis    : Cash basis\n"
    "Functional currency : EUR\n"
    "Fiscal year start   : 01-01\n"
    "Posting coverage    : All posting kinds\n"
    "Account             : Cash [cash]\n"
    "Account type        : Asset\n"
    "Normal balance      : Debit\n"
    "Active              : Yes\n"
)
STANDARD_TRIAL_BALANCE_TEXT = (
    "Trial Balance\n"
    "As of : 2026-04-08\n"
    "cash | 6.00\n"
    "Context\n"
    "-------\n"
    "Entity              : Acme Studio\n"
    "Seed template       : Owner-managed service seed template\n"
    "Accounting basis    : Cash basis\n"
    "Functional currency : EUR\n"
    "Fiscal year start   : 01-01\n"
    "Posting coverage    : All posting kinds\n"
)
STANDARD_PERIOD_SUMMARY_TEXT = "Period Summary\nPosting count : 2\n"


def pdf_export_stdout(reported_path: str) -> str:
    return f"Artifact\n========\n\nFormat : pdf\nPath   : {reported_path}\n"
