fingrindJavaVersion=26
implementationVendor=Ervins Strauhmanis
implementationLicense=MIT
foojayResolverConventionVersion=1.0.0
fingrindJacocoSnapshotBuild=0.8.15.202604281210
fingrindJacocoSnapshotResolvedVersion=0.8.15-20260428.121054-96
