#!/usr/bin/env python3
"""Validate, project, compare, regenerate, or recover the public Ledger-1 remediation plan."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from remediation_plan_projection import check, generate, project
from remediation_plan_recovery import recover
from remediation_plan_support import RemediationError
from remediation_plan_validation import validate_public_projection


class _Parser(argparse.ArgumentParser):
    def error(self, message: str) -> None:
        raise RemediationError(message)


def _repository_root() -> Path:
    script = Path(__file__).resolve()
    for candidate in (script.parent, *script.parents):
        if (candidate / ".git").exists() and (candidate / "settings.gradle.kts").is_file():
            return candidate
    raise RemediationError("cannot discover the FinGrind repository from this script")


def _arguments() -> argparse.Namespace:
    parser = _Parser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("validate", help="perform read-only public projection validation")
    commands.add_parser("check", help="compare validated artifacts with fixed generated bytes")
    commands.add_parser("generate", help="transactionally reinstall validated generated bytes")
    recovery = commands.add_parser("recover", help="recover one interrupted remediation operation")
    recovery.add_argument("--operation-id", required=True)
    projection = commands.add_parser(
        "project", help="validate private authority and install the public projection"
    )
    projection.add_argument("--restricted-root", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    try:
        arguments = _arguments()
        root = _repository_root()
        if arguments.command == "validate":
            validate_public_projection(root)
            print("remediation-plan: validation PASS")
        elif arguments.command == "check":
            check(root)
            print("remediation-plan: generated-byte check PASS")
        elif arguments.command == "generate":
            operation_id = generate(root)
            print(f"remediation-plan: generation PASS operation={operation_id}")
        elif arguments.command == "recover":
            if re.fullmatch(r"[0-9a-f]{32}", arguments.operation_id) is None:
                raise RemediationError(
                    "operation ID must be a lowercase 32-character hexadecimal value"
                )
            recover(root, arguments.operation_id)
            print(f"remediation-plan: recovery PASS operation={arguments.operation_id}")
        else:
            operation_id = project(root, arguments.restricted_root.resolve())
            print(f"remediation-plan: projection PASS operation={operation_id}")
    except RemediationError as error:
        print(f"remediation-plan: {error}", file=sys.stderr)
        return 1
    except OSError as error:
        print(f"remediation-plan: runtime failure: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
