"""Table-to-section ownership for the canonical SQLite schema reference."""

TABLE_SECTION_BY_NAME = {
    "book_meta": "foundation",
    "book_identity": "foundation",
    "account": "account-table",
    "tax_registration": "tax-registration",
    "tax_registration_code": "tax-registration",
    "posting_fact": "posting-fact",
    "posting_source_document": "posting-source-document",
    "posting_approval": "posting-approval",
    "posting_foreign_exchange": "posting-foreign-exchange",
    "posting_applied_tax": "posting-applied-tax",
    "journal_line": "journal-lines",
    "inventory_movement": "inventory-movement",
    "inventory_on_hand": "inventory-on-hand",
    "accrual_cutoff": "accrual-cutoff",
    "accrual_cutoff_application": "accrual-cutoff-applications",
    "latvian_payroll_run": "latvian-payroll-runs",
    "latvian_payroll_run_reversal": "latvian-payroll-runs",
    "latvian_payroll_settlement": "latvian-payroll-settlements",
    "latvian_payroll_settlement_reversal": "latvian-payroll-settlements",
    "fixed_asset": "fixed-assets",
    "fixed_asset_application": "fixed-assets",
    "fixed_asset_reversal": "fixed-assets",
    "fixed_asset_application_reversal": "fixed-assets",
    "financing_arrangement": "financing",
    "financing_application": "financing",
    "financing_arrangement_reversal": "financing",
    "financing_application_reversal": "financing",
    "foreign_currency_obligation": "realized-foreign-exchange",
    "foreign_currency_obligation_settlement": "realized-foreign-exchange",
    "foreign_currency_obligation_reversal": "realized-foreign-exchange",
    "foreign_currency_obligation_settlement_reversal": "realized-foreign-exchange",
    "interim_result_sweep": "interim-result-sweep-core",
    "interim_result_sweep_total": "interim-result-sweep-links",
    "interim_result_sweep_posting": "interim-result-sweep-links",
    "fiscal_year_close": "fiscal-year-close-table",
    "fiscal_year_close_posting": "fiscal-year-close-links",
    "audit_event": "audit-events",
}
