"""Trigger-to-section ownership for the canonical SQLite schema reference."""

TRIGGER_SECTION_BY_PREFIX = (
    ("account_validate_", "account-rules"),
    ("account_reject_", "account-rules"),
    ("tax_registration_validate_", "tax-registration"),
    ("tax_registration_reject_", "tax-registration"),
    ("posting_fact_validate_", "posting-fact-admission"),
    ("posting_fact_reject_", "indexes-and-immutability"),
    ("posting_foreign_exchange_validate_", "posting-foreign-exchange"),
    ("posting_foreign_exchange_reject_", "posting-foreign-exchange"),
    ("posting_applied_tax_validate_", "posting-applied-tax"),
    ("posting_applied_tax_reject_", "posting-applied-tax"),
    ("journal_line_validate_", "journal-lines"),
    ("journal_line_reject_", "indexes-and-immutability"),
    ("inventory_movement_validate_", "inventory-movement"),
    ("inventory_movement_reject_", "indexes-and-immutability"),
    ("inventory_on_hand_validate_", "inventory-on-hand"),
    ("accrual_cutoff_validate_", "accrual-cutoff"),
    ("accrual_cutoff_application_validate_", "accrual-cutoff-applications"),
    ("accrual_cutoff_reject_", "accrual-cutoff-applications"),
    ("accrual_cutoff_application_reject_", "accrual-cutoff-applications"),
    ("latvian_payroll_run_reversal_reject_", "latvian-payroll-run-immutability"),
    ("latvian_payroll_run_reject_", "latvian-payroll-run-immutability"),
    ("latvian_payroll_run_", "latvian-payroll-runs"),
    ("latvian_payroll_settlement_", "latvian-payroll-settlements"),
    ("fixed_asset_", "fixed-assets"),
    ("financing_", "financing"),
    ("foreign_currency_obligation_", "realized-foreign-exchange"),
    ("book_identity_reject_", "indexes-and-immutability"),
    ("interim_result_sweep_validate_", "interim-result-sweep-core"),
    ("interim_result_sweep_reject_", "indexes-and-immutability"),
    ("interim_result_sweep_total_reject_", "indexes-and-immutability"),
    ("interim_result_sweep_posting_validate_", "interim-result-sweep-links"),
    ("interim_result_sweep_posting_reject_", "indexes-and-immutability"),
    ("fiscal_year_close_validate_", "fiscal-year-close-target-rules"),
    ("fiscal_year_close_reject_", "indexes-and-immutability"),
    ("fiscal_year_close_posting_validate_", "fiscal-year-close-links"),
    ("fiscal_year_close_posting_reject_", "indexes-and-immutability"),
    ("audit_event_validate_", "audit-events"),
    ("audit_event_reject_", "indexes-and-immutability"),
)
