"""Canonical schema-doc section ownership for the SQLite schema renderer."""

from dataclasses import dataclass


@dataclass(frozen=True)
class SchemaSection:
    key: str
    file_name: str
    title: str
    purpose: str
    coverage: str
    domain: str


SECTIONS = [
    SchemaSection(
        key="foundation",
        file_name="SCHEMA_CORE_01_FOUNDATION.md",
        title="SQLite Schema: Foundation",
        purpose="Application id, format version, book metadata, and book identity bootstrap.",
        coverage="`pragma application_id`, `pragma user_version`, `book_meta`, and `book_identity`.",
        domain="SQLITE_SCHEMA_CORE_FOUNDATION",
    ),
    SchemaSection(
        key="account-table",
        file_name="SCHEMA_CORE_02_ACCOUNT_TABLE.md",
        title="SQLite Schema: Account Table",
        purpose="Declared-account storage, classifications, and parent pointers.",
        coverage="`account`.",
        domain="SQLITE_SCHEMA_CORE_ACCOUNT_TABLE",
    ),
    SchemaSection(
        key="account-rules",
        file_name="SCHEMA_CORE_03_ACCOUNT_RULES.md",
        title="SQLite Schema: Account Rules",
        purpose="Parent-shape invariants and account immutability triggers.",
        coverage="Account parent validation and account append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_ACCOUNT_RULES",
    ),
    SchemaSection(
        key="tax-registration",
        file_name="SCHEMA_CORE_03z_TAX_REGISTRATION.md",
        title="SQLite Schema: Tax Registration",
        purpose="Declared tax registrations, tax-code doctrine, registration-account validation, and tax-registration append-only rules.",
        coverage="`tax_registration`, `tax_registration_code`, and tax-registration validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_TAX_REGISTRATION",
    ),
    SchemaSection(
        key="posting-fact",
        file_name="SCHEMA_CORE_04_POSTING_FACT.md",
        title="SQLite Schema: Posting Fact",
        purpose="Persisted posting identity, provenance, and replay fingerprint.",
        coverage="`posting_fact`.",
        domain="SQLITE_SCHEMA_CORE_POSTING_FACT",
    ),
    SchemaSection(
        key="posting-fact-admission",
        file_name="SCHEMA_CORE_04z_POSTING_FACT_ADMISSION.md",
        title="SQLite Schema: Posting Fact Admission",
        purpose="Posting effective-date, close-provenance, and opening-window admission gates.",
        coverage="Posting-fact admission triggers.",
        domain="SQLITE_SCHEMA_CORE_POSTING_FACT_ADMISSION",
    ),
    SchemaSection(
        key="posting-source-document",
        file_name="SCHEMA_CORE_05_POSTING_SOURCE_DOCUMENT.md",
        title="SQLite Schema: Posting Source Documents",
        purpose="Durable source-document attribution for committed postings.",
        coverage="`posting_source_document`.",
        domain="SQLITE_SCHEMA_CORE_POSTING_SOURCE_DOCUMENT",
    ),
    SchemaSection(
        key="posting-approval",
        file_name="SCHEMA_CORE_06_POSTING_APPROVAL.md",
        title="SQLite Schema: Posting Approvals",
        purpose="Durable approval references for committed postings.",
        coverage="`posting_approval`.",
        domain="SQLITE_SCHEMA_CORE_POSTING_APPROVAL",
    ),
    SchemaSection(
        key="posting-applied-tax",
        file_name="SCHEMA_CORE_06z_POSTING_APPLIED_TAX.md",
        title="SQLite Schema: Posting Applied Tax",
        purpose="Per-posting resolved tax facts, posting-origin tax admissibility rules, and applied-tax append-only enforcement.",
        coverage="`posting_applied_tax` and posting-applied-tax validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_POSTING_APPLIED_TAX",
    ),
    SchemaSection(
        key="posting-foreign-exchange",
        file_name="SCHEMA_CORE_06za_POSTING_FOREIGN_EXCHANGE.md",
        title="SQLite Schema: Posting Foreign Exchange",
        purpose="Per-posting owned foreign-exchange facts, posting-origin and functional-currency admissibility rules, and foreign-exchange append-only enforcement.",
        coverage="`posting_foreign_exchange` and posting-foreign-exchange validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_POSTING_FOREIGN_EXCHANGE",
    ),
    SchemaSection(
        key="journal-lines",
        file_name="SCHEMA_CORE_07_JOURNAL_LINES.md",
        title="SQLite Schema: Journal Lines",
        purpose="Committed journal-line storage and journal-line-side admission gates.",
        coverage="`journal_line` and journal-line validation triggers.",
        domain="SQLITE_SCHEMA_CORE_JOURNAL_LINES",
    ),
    SchemaSection(
        key="inventory-movement",
        file_name="SCHEMA_CORE_07z_INVENTORY_MOVEMENT.md",
        title="SQLite Schema: Inventory Movement Ledger",
        purpose="Append-only inventory movement replay, ordering, provenance, and opening-balance admission gates.",
        coverage="`inventory_movement` and inventory-movement validation triggers.",
        domain="SQLITE_SCHEMA_CORE_INVENTORY_MOVEMENT",
    ),
    SchemaSection(
        key="inventory-on-hand",
        file_name="SCHEMA_CORE_07za_INVENTORY_ON_HAND.md",
        title="SQLite Schema: Inventory On-Hand State",
        purpose="Materialized quantity and cost-pool state plus inventory-account admission gates.",
        coverage="`inventory_on_hand` and inventory-on-hand validation triggers.",
        domain="SQLITE_SCHEMA_CORE_INVENTORY_ON_HAND",
    ),
    SchemaSection(
        key="interim-result-sweep-core",
        file_name="SCHEMA_CORE_08_INTERIM_RESULT_SWEEP_CORE.md",
        title="SQLite Schema: Interim Result Sweep Core",
        purpose="Sweep-range facts and target-account doctrine for contiguous interim closes.",
        coverage="`interim_result_sweep` and interim-result-sweep range/target triggers.",
        domain="SQLITE_SCHEMA_CORE_INTERIM_RESULT_SWEEP_CORE",
    ),
    SchemaSection(
        key="interim-result-sweep-links",
        file_name="SCHEMA_CORE_09_INTERIM_RESULT_SWEEP_LINKS.md",
        title="SQLite Schema: Interim Result Sweep Links",
        purpose="Per-currency sweep totals and generated sweep-posting linkage.",
        coverage="`interim_result_sweep_total`, `interim_result_sweep_posting`, and posting-link validation triggers.",
        domain="SQLITE_SCHEMA_CORE_INTERIM_RESULT_SWEEP_LINKS",
    ),
    SchemaSection(
        key="fiscal-year-close-table",
        file_name="SCHEMA_CORE_10_FISCAL_YEAR_CLOSE_TABLE.md",
        title="SQLite Schema: Fiscal Year Close Table",
        purpose="Year-close range facts and required target-account pointers.",
        coverage="`fiscal_year_close`.",
        domain="SQLITE_SCHEMA_CORE_FISCAL_YEAR_CLOSE_TABLE",
    ),
    SchemaSection(
        key="fiscal-year-close-target-rules",
        file_name="SCHEMA_CORE_11_FISCAL_YEAR_CLOSE_TARGET_RULES.md",
        title="SQLite Schema: Fiscal Year Close Target Rules",
        purpose="Capital, result-holding, and retained-accumulated target-account validation.",
        coverage="Fiscal-year-close target-account validation trigger.",
        domain="SQLITE_SCHEMA_CORE_FISCAL_YEAR_CLOSE_TARGET_RULES",
    ),
    SchemaSection(
        key="fiscal-year-close-links",
        file_name="SCHEMA_CORE_12_FISCAL_YEAR_CLOSE_LINKS.md",
        title="SQLite Schema: Fiscal Year Close Links",
        purpose="Generated fiscal-year-close posting linkage and posting-side invariants.",
        coverage="`fiscal_year_close_posting` and posting-link validation triggers.",
        domain="SQLITE_SCHEMA_CORE_FISCAL_YEAR_CLOSE_LINKS",
    ),
    SchemaSection(
        key="audit-events",
        file_name="SCHEMA_CORE_13_AUDIT_EVENTS.md",
        title="SQLite Schema: Audit Events",
        purpose="Append-only audit-event storage for lifecycle, posting, and close-operation facts.",
        coverage="`audit_event` and close-operation audit validation trigger.",
        domain="SQLITE_SCHEMA_CORE_AUDIT_EVENTS",
    ),
    SchemaSection(
        key="accrual-cutoff",
        file_name="SCHEMA_CORE_13z_ACCRUAL_CUTOFF.md",
        title="SQLite Schema: Accrual Cut-off Aggregate",
        purpose="Durable origins for accrual-basis prepayments, deferred revenue, and accrued expenses.",
        coverage="`accrual_cutoff` and origin-account and origin-posting validation triggers.",
        domain="SQLITE_SCHEMA_CORE_ACCRUAL_CUTOFF",
    ),
    SchemaSection(
        key="accrual-cutoff-applications",
        file_name="SCHEMA_CORE_13za_ACCRUAL_CUTOFF_APPLICATIONS.md",
        title="SQLite Schema: Accrual Cut-off Applications",
        purpose="Append-only recognition, settlement, and compensating-reversal facts for accrual cut-offs.",
        coverage="`accrual_cutoff_application`, lifecycle application validation, and accrual-cut-off append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_ACCRUAL_CUTOFF_APPLICATIONS",
    ),
    SchemaSection(
        key="fixed-assets",
        file_name="SCHEMA_CORE_13zb_FIXED_ASSETS.md",
        title="SQLite Schema: Fixed-Asset Lifecycle",
        purpose="Immutable fixed-asset capitalizations plus depreciation and disposal applications.",
        coverage="`fixed_asset`, `fixed_asset_application`, compensating reversal links, and lifecycle validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_FIXED_ASSETS",
    ),
    SchemaSection(
        key="financing",
        file_name="SCHEMA_CORE_13zc_FINANCING.md",
        title="SQLite Schema: Financing Lifecycle",
        purpose="Immutable borrowing arrangements plus principal and interest applications.",
        coverage="`financing_arrangement`, `financing_application`, compensating reversal links, and lifecycle validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_FINANCING",
    ),
    SchemaSection(
        key="realized-foreign-exchange",
        file_name="SCHEMA_CORE_13zd_REALIZED_FOREIGN_EXCHANGE.md",
        title="SQLite Schema: Realized Foreign-Exchange Settlement",
        purpose="Foreign-currency receivable obligations and their one-time realized-settlement facts.",
        coverage="`foreign_currency_obligation`, `foreign_currency_obligation_settlement`, compensating reversal links, and lifecycle validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_REALIZED_FOREIGN_EXCHANGE",
    ),
    SchemaSection(
        key="latvian-payroll",
        file_name="SCHEMA_CORE_13ze_LATVIAN_PAYROLL.md",
        title="SQLite Schema: Latvian Payroll Lifecycle",
        purpose="Immutable Latvian monthly-payroll runs, obligation settlements, and compensating reversals.",
        coverage="`latvian_payroll_run`, `latvian_payroll_settlement`, their reversal links, and lifecycle validation/append-only triggers.",
        domain="SQLITE_SCHEMA_CORE_LATVIAN_PAYROLL",
    ),
    SchemaSection(
        key="indexes-and-immutability",
        file_name="SCHEMA_CORE_14_INDEXES_AND_IMMUTABILITY.md",
        title="SQLite Schema: Indexes And Immutability",
        purpose="Lookup indexes plus append-only triggers for durable rows that never mutate in place.",
        coverage="Schema-tail lookup indexes and append-only reject-update/reject-delete triggers.",
        domain="SQLITE_SCHEMA_CORE_INDEXES_AND_IMMUTABILITY",
    ),
]
SECTION_BY_KEY = {section.key: section for section in SECTIONS}
