package dev.erst.fingrind.buildlogic

internal val reviewedJavaContractAndCliSourceSurfaces =
    listOf(
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/contract/bookkeeping/RejectionNarrative.java",
            owner = "contract-bookkeeping",
            reason =
                "The published bookkeeping rejection narrative remains one explicit language catalog for stable public refusal text.",
            splitTrigger =
                "Split by rejection family before adding another unrelated narrative vocabulary branch.",
            roleName = "bookkeeping-rejection-narrative",
            physicalLines = 231,
            logicalLines = 223,
            imports = 4,
            nestedTypes = 8,
            methodsPerTopLevelType = 20,
            fieldsPerTopLevelType = 10,
            switchArmsPerMethod = 20,
            methodLineSpan = 140,
            methodParameters = 12,
            methodDecisionPoints = 24,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/contract/discovery/ContractTemplates.java",
            owner = "protocol-discovery",
            reason =
                "The public discovery template namespace owns one deliberate published contract family instead of hiding that catalog across adjacent files.",
            splitTrigger =
                "Split by request-template or plan-step family before adding another independent template branch.",
            roleName = "contract-template-namespace",
            physicalLines = 391,
            logicalLines = 373,
            imports = 34,
            nestedTypes = 16,
            methodsPerTopLevelType = 18,
            fieldsPerTopLevelType = 12,
            switchArmsPerMethod = 10,
            methodLineSpan = 70,
            methodParameters = 8,
            methodDecisionPoints = 16,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/cli/json/CliDiscoveryJsonModels.java",
            owner = "cli-json-contract",
            reason =
                "Discovery JSON remains one machine-contract family, but it is reviewed as a frozen large surface rather than normalized as the package default.",
            splitTrigger =
                "Split by capabilities, help, and environment payload families before adding another discovery JSON namespace.",
            roleName = "cli-discovery-json-aggregate",
            physicalLines = 419,
            logicalLines = 395,
            imports = 23,
            nestedTypes = 50,
            methodsPerTopLevelType = 18,
            fieldsPerTopLevelType = 18,
            switchArmsPerMethod = 10,
            methodLineSpan = 60,
            methodParameters = 6,
            methodDecisionPoints = 14,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/cli/json/CliPlanJsonModels.java",
            owner = "cli-json-contract",
            reason =
                "Ledger-plan JSON remains one machine-contract family, but it is reviewed as a frozen large surface instead of inheriting a broad package waiver.",
            splitTrigger =
                "Split by execution envelope, fact, and rejection payload families before adding another plan JSON namespace.",
            roleName = "cli-plan-json-aggregate",
            physicalLines = 368,
            logicalLines = 340,
            imports = 14,
            nestedTypes = 40,
            methodsPerTopLevelType = 18,
            fieldsPerTopLevelType = 18,
            switchArmsPerMethod = 10,
            methodLineSpan = 60,
            methodParameters = 6,
            methodDecisionPoints = 14,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/cli/json/CliRejectionJsonModels.java",
            owner = "cli-json-contract",
            reason =
                "The rejection JSON aggregate remains one explicit machine-contract namespace, with the public rejection envelope vocabulary grouped in one place.",
            splitTrigger =
                "Split by rejection family before adding another unrelated rejection namespace or serializer concern.",
            roleName = "cli-rejection-json-aggregate",
            physicalLines = 413,
            logicalLines = 366,
            imports = 6,
            nestedTypes = 50,
            methodsPerTopLevelType = 18,
            fieldsPerTopLevelType = 18,
            switchArmsPerMethod = 10,
            methodLineSpan = 60,
            methodParameters = 6,
            methodDecisionPoints = 14,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/cli/json/CliReportJsonModels.java",
            owner = "cli-json-contract",
            reason =
                "Report JSON remains one machine-contract family, but it is reviewed as a frozen large surface instead of being treated as a normal-size DTO file.",
            splitTrigger =
                "Split by report family before adding another statement or export payload namespace.",
            roleName = "cli-report-json-aggregate",
            physicalLines = 333,
            logicalLines = 314,
            imports = 8,
            nestedTypes = 40,
            methodsPerTopLevelType = 18,
            fieldsPerTopLevelType = 18,
            switchArmsPerMethod = 10,
            methodLineSpan = 60,
            methodParameters = 6,
            methodDecisionPoints = 14,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/contract/protocol/ProtocolAdministrationOperations.java",
            owner = "protocol-catalog",
            reason =
                "The administration operation inventory is one reviewed protocol catalog surface rather than hidden accumulation across adjacent public files.",
            splitTrigger =
                "Split by operation family before adding another independently published administration contract cluster.",
            roleName = "protocol-administration-catalog",
            physicalLines = 272,
            logicalLines = 268,
            imports = 1,
            nestedTypes = 10,
            methodsPerTopLevelType = 22,
            fieldsPerTopLevelType = 12,
            switchArmsPerMethod = 20,
            methodLineSpan = 320,
            methodParameters = 16,
            methodDecisionPoints = 24,
        ),
        reviewedJavaSourceSurface(
            relativePath = "src/main/java/dev/erst/fingrind/contract/protocol/ProtocolQueryOperations.java",
            owner = "protocol-catalog",
            reason =
                "The query operation inventory is one reviewed protocol catalog surface rather than implicit spread across adjacent public files.",
            splitTrigger =
                "Split by query family before adding another independently published query contract cluster.",
            roleName = "protocol-query-catalog",
            physicalLines = 310,
            logicalLines = 290,
            imports = 2,
            nestedTypes = 10,
            methodsPerTopLevelType = 22,
            fieldsPerTopLevelType = 12,
            switchArmsPerMethod = 20,
            methodLineSpan = 360,
            methodParameters = 16,
            methodDecisionPoints = 24,
        ),
    )
